### ISSUE TITLE
compile errors in QT and Visual Studio on windows

### ISSUE THREAD

**Issue by ShovelHand** [luckysama/icg#5]
I pulled the latest icg with glew and glfw libraries for windows builds, but I'm still having trouble compiling in either IDE. Visual Studio gives me 12 link errors for for LIBCMT.lib and MSVCRT.lib, like
Error   30  error LNK2005: _strchr already defined in LIBCMT.lib(strchr.obj)    C:\icg-build\introglsl\MSVCRT.lib(MSVCR120.dll) introglsl
or,
Error   31  error LNK2005: _free already defined in LIBCMT.lib(free.obj)    C:\icg-build\introglsl\MSVCRT.lib(MSVCR120.dll) introglsl.

With QT I get the following three errors;
C:\icg\external\glew\lib\win32\glew32s.lib(tmp\glew_static\Release\Win32\glew.obj):-1: error: undefined reference to `_imp__wglGetProcAddress@4'
C:\icg\external\glew\lib\win32\glew32s.lib(tmp\glew_static\Release\Win32\glew.obj):-1: error: undefined reference to`_imp__wglGetProcAddress@4'
:-1: error: C:/icg/external/glew/lib/win32/glew32s.lib(tmp/glew_static/Release/Win32/glew.obj): bad reloc address 0x4 in section `.text$mn'

I suspect I need some kind of #ifndef compile guard in there for using the appropriate library, but I have no idea where it would go.
Any help would be appreciated.

**Comment by taiya** [comment]
Try to switch compiling in 32bits / 64bits

**Comment by ShovelHand** [comment]
Wasn't able to get it to work doing that. I'll try recompiling the glew and glfw libraries using MSVCRT and see if that clears up the linking problem.

**Comment by taiya** [comment]
I don't have a windows machine to work on, thus unfortunately I cannot be of too much help. 
I can only address Linux / UNIX problems and fully support problems in the lab.

If you find a solution, please do share it!

**Comment by taiya** [comment]
A fellow student has mentioned you can use the G++ in MingGW. The intel C++ compiler would be my personal pick, as then we'd have a solution that doesn't become obsolete every time Microsoft releases a new compiler.

The quickest solution is still to install Ubuntu on a dual-partition (with proper graphics drivers)
Note you **CANNOT** use virtual machines. They typically only support ~OpenGL2

**Comment by sg16nop** [comment]
The following solution worked for me. Say you've just pulled from the origin and you are using visual studio...

1) select the project you want to compile. Then go to project->properties->Configuration properties->C/C++->Code generation, Change the runtime library to "MDd". This should resolve the conflict with the pre-compiled GLFW library
(For this part, I think the trick with /NODEFAULTLIB on the other issue post works too)

2) go to highest the cmake file and comment out the the line that includes opencv
(I suspect that the opencv library and the GLEW/GLFW are compiled differently too)

3) change all the shader paths in you code like this: "/vshader.glsl" becomes "../vshader.glsl".
This is because Visual Studio puts the .exe file in a debug or release folder in the target location. If you know how actually change the exact output path, please let me know.

4) build the selected project, then run its .exe directly.
(for some reason, relative paths always cause problems for me if I launch the program from VS)

Hope this helps!
Douglas

**Comment by sg16nop** [comment]
Actually, ignore step 1). Just getting rid of opencv seems to work too :p

**Comment by jordan-heemskerk** [comment]
@sg16nop Awesome tips! Finally got it working at home with your steps!

@ataiya Maybe worth a 1% for @sg16nop...

**Comment by sg16nop** [comment]
@jordan-heemskerk No problem man. Took me couple of hours track this one down, and there is absolute no point for fellow windows users to go through the same pain.

**Comment by jordan-heemskerk** [comment]
Also, instead of changing the shader paths, if you right-click the project in VS, you can change the Output Directory of the exe to be whatever you want instead of the Debug subdir.
![image](https://cloud.githubusercontent.com/assets/4603704/10560645/19529154-74c6-11e5-91fa-02fb26215600.png)

**Comment by luckysama** [comment]
@jordan-heemskerk @ShovelHand , Please take a look at the other issue post
https://github.com/luckysama/icg/issues/6
See if information there helps.

**Comment by taiya** [comment]
Yes, I think @sg16nop deserves the 1%. 
There is only one Douglas (Wong) in the roster.

Let me know if this is not correct.
